### ISSUE TITLE
No matching distribution found for torch==1.13.1+cu117 on a machine with no GPU

### ISSUE THREAD

**Issue by maxwellcheng** [yftzeng/stable-diffusion-webui-docker#4]
hi, thanks for the fix.
I run in to another issue : **No matching distribution found for torch==1.13.1+cu117**
when running **profile cpu** up -d, 
it is exactly as below issue:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7166
My environment is a ubuntu with no GPU, is there any work around to run the webui?
thanks a lot for your effort.

**Comment by yftzeng** [comment]
The commit 7caf371d67f1d731e9a1a96196f3df5e89de5e53 try to solve this problem, although this question is taught by stable-diffusion-webui, please try again.
